Repository j2commerce/j2cart, pull requests merged in 2024-10, with the labels that each got.

#19 function removeFlexiAllVariant
  administrator/components/com_j2store/views/product/tmpl/form_flexivariablevariants.php
Labels: typos

#18 variable name
  administrator/components/com_j2store/library/plugins/payment.php
Labels: typos

#17 shipping_avaliable property
  administrator/components/com_j2store/controllers/shippingtroubles.php
  administrator/components/com_j2store/views/shippingtroubles/tmpl/default_shipping.php
  administrator/components/com_j2store/views/shippingtroubles/tmpl/default_shipping_product.php
Labels: typos

#15 spelling and typo fixes in comments
  administrator/components/com_j2store/controllers/cpanels.php
  administrator/components/com_j2store/helpers/currency.php
  administrator/components/com_j2store/helpers/email.php
  administrator/components/com_j2store/helpers/j2html.php
  administrator/components/com_j2store/helpers/user.php
  administrator/components/com_j2store/helpers/utilities.php
  administrator/components/com_j2store/library/plugins/app.php
  administrator/components/com_j2store/library/plugins/report.php
  administrator/components/com_j2store/library/plugins/shipping.php
  administrator/components/com_j2store/library/selectable/base.php
  administrator/components/com_j2store/models/cartadmins.php
  administrator/components/com_j2store/models/carts.php
  administrator/components/com_j2store/models/coupons.php
  administrator/components/com_j2store/models/fields/couponexpiretext.php
  administrator/components/com_j2store/models/myprofiles.php
  administrator/components/com_j2store/models/orderdownloads.php
  administrator/components/com_j2store/models/orders.php
  administrator/components/com_j2store/models/products.php
  administrator/components/com_j2store/models/producttags.php
  administrator/components/com_j2store/models/vouchers.php
  administrator/components/com_j2store/tables/order.php
  administrator/components/com_j2store/tables/variant.php
  administrator/components/com_j2store/views/coupon/tmpl/products.php
  administrator/components/com_j2store/views/product/tmpl/form.php
  administrator/components/com_j2store/views/product/tmpl/form_images.php
  administrator/components/com_j2store/views/products/tmpl/couponproducts.php
  components/com_j2store/controllers/checkouts.php
  components/com_j2store/controllers/products.php
  components/com_j2store/controllers/producttags.php
  modules/admin/j2store_chart/tmpl/default.php
  plugins/j2store/payment_cash/payment_cash.php
  plugins/j2store/payment_moneyorder/payment_moneyorder.php
  plugins/j2store/payment_paypal/payment_paypal.php
  plugins/j2store/payment_sagepayform/payment_sagepayform.php
  plugins/j2store/report_itemised/report_itemised/models/reportitemised.php
  plugins/j2store/report_products/report_products.php
  plugins/j2store/shipping_standard/shipping_standard.php
  script.j2store.php
Labels: typos

#14 variable name
  administrator/components/com_j2store/helpers/strapper.php
Labels: typos

#12 Language string J2STORE_J2USERREGISTER_FIELDS_HTML
  language/backend/en-GB/en-GB.com_j2store.ini
  plugins/user/j2userregister/j2userregister.xml
Labels: typos

#11 language strings agreement
  plugins/j2store/payment_paypal/languages/en-GB.plg_j2store_payment_paypal.ini
  plugins/j2store/payment_paypal/payment_paypal.xml
Labels: typos

#10 set valid message type
  administrator/components/com_j2store/controllers/orders.php
  plugins/content/j2store/j2store.php
Labels: bug, typos

#9 function getdimensions
  administrator/components/com_j2store/controllers/productbase.php
  administrator/components/com_j2store/models/behavior/flexivariable.php
  administrator/components/com_j2store/models/behavior/variable.php
  administrator/components/com_j2store/models/variants.php
Labels: typos

#8 invalid markup
  plugins/j2store/shipping_standard/shipping_standard/tmpl/view.php
Labels: bug, typos

#7 function byReference
  plugins/j2store/payment_paypal/payment_paypal.php
Labels: typos

#6 variable tomorrow
  modules/admin/j2store_stats/tmpl/default.php
  modules/admin/j2store_stats_mini/tmpl/default.php
Labels: typos

#5 function buildQuery
  administrator/components/com_j2store/models/shippingtroubles.php
Labels: typos

#3 function getJ2storeVersion
  plugins/j2store/app_diagnostics/app_diagnostics.php
Labels: typos

#2 variable absoluteHeightMultipler
  plugins/j2store/report_products/report_products/js/material-charts.js
Labels: typos

#1 13 variant
  administrator/components/com_j2store/models/behavior/flexivariable.php
  administrator/components/com_j2store/models/behavior/variable.php
  administrator/components/com_j2store/views/product/tmpl/form_flexivariablevariants.php
  plugins/j2store/app_flexivariable/app_flexivariable/controller.php
Labels: typos

#16 param hide_shipping_untill_address_selection
  administrator/components/com_j2store/controllers/configurations.php
  components/com_j2store/views/carts/view.html.php
Labels: typos

#4 array orginal
  administrator/components/com_j2store/models/behavior/configurable.php
  administrator/components/com_j2store/models/behavior/downloadable.php
  administrator/components/com_j2store/models/behavior/flexivariable.php
  administrator/components/com_j2store/models/behavior/simple.php
  administrator/components/com_j2store/models/behavior/variable.php
Labels: typos

#23 expresscheckout
  plugins/j2store/payment_paypal/payment_paypal.php
Labels: typos

#24 xml tidy
  administrator/components/com_j2store/config.xml
  components/com_j2store/views/checkout/tmpl/postpayment.xml
  components/com_j2store/views/products/tmpl/default.xml
  components/com_j2store/views/producttags/tmpl/default.xml
  modules/admin/j2store_chart/mod_j2store_chart.xml
  modules/admin/j2store_stats/mod_j2store_stats.xml
  modules/admin/j2store_stats_mini/mod_j2store_stats_mini.xml
  modules/site/mod_j2store_cart/mod_j2store_cart.xml
  modules/site/mod_j2store_currency/mod_j2store_currency.xml
  plugins/content/j2store/forms/j2store.xml
  plugins/content/j2store/j2store.xml
  plugins/finder/j2store/j2store.xml
  plugins/j2store/app_currencyupdater/app_currencyupdater.xml
  plugins/j2store/app_flexivariable/app_flexivariable.xml
  plugins/j2store/payment_banktransfer/payment_banktransfer.xml
  plugins/j2store/payment_cash/payment_cash.xml
  plugins/j2store/payment_moneyorder/payment_moneyorder.xml
  plugins/j2store/payment_paypal/payment_paypal.xml
  plugins/j2store/payment_sagepayform/payment_sagepayform.xml
  plugins/j2store/shipping_free/shipping_free.xml
  plugins/search/j2store/j2store.xml
  plugins/system/j2canonical/j2canonical.xml
  plugins/system/j2pagecache/j2pagecache.xml
  plugins/system/j2store/j2store.xml
  plugins/user/j2userregister/fields/j2storecustom.xml
  plugins/user/j2userregister/j2userregister.xml
Labels: typos, tidy up

#26 invalid language strings
  administrator/components/com_j2store/controllers/productbase.php
  administrator/components/com_j2store/models/coupons.php
  language/backend/en-GB/en-GB.com_j2store.ini
Labels: bug

#27 Missing mediaTypeNames attribute for media field
  administrator/components/com_j2store/helpers/j2html.php
Labels: bug

#38 Duplicated attribute 'class' prevents the form to load
  components/com_j2store/views/products/tmpl/default.xml
Labels: bug

#37 Fix Joomla 4 FA icon + Joomla 5 name spacing
  administrator/components/com_j2store/helpers/help.php
Labels: bug, tidy up

#39 Product Category/Tag Menu Cleanup
  administrator/components/com_j2store/models/fields/tagtemplatelist.php
  administrator/components/com_j2store/models/fields/templatelist.php
  components/com_j2store/views/producttags/tmpl/default.xml
  language/backend/en-GB/en-GB.com_j2store.ini
Labels: tidy up, refactoring

#41 Removed deprecation ${var] -> {$var}
  fof/less/less.php
Labels: bug

#40 Products view fields cleanup
  components/com_j2store/views/products/tmpl/default.xml
Labels: tidy up

#42 Updated version # 4.0.7
  administrator/components/com_j2store/version.php
Labels: tidy up

#43 Update com_j2store.xml for 4.0.7 release
  com_j2store.xml
Labels: tidy up

#44 fix array_merge() error by ensuring $templateFolders is always an array of directory names
  administrator/components/com_j2store/models/fields/tagtemplatelist.php
  administrator/components/com_j2store/models/fields/templatelist.php
Labels: bug

#46 email editor fix (broken since 4.0) + general Joomla 5 cleanup
  administrator/components/com_j2store/controllers/emailtemplates.php
  administrator/components/com_j2store/helpers/j2html.php
  administrator/components/com_j2store/layouts/edit/email_tab.php
  language/backend/en-GB/en-GB.com_j2store.ini
  media/j2store/css/J4/j2store_admin.css
Labels: bug, tidy up

#47 Prevent the loading of FontAwesome 4 and fix when missing style in the active assets
  administrator/components/com_j2store/layouts/joomla/sidebars/submenu.php
  modules/admin/j2store_menu/tmpl/default.php
Labels: bug

#48 Usergroup list 'all' value should be empty or else SQL error
  administrator/components/com_j2store/controllers/emailtemplates.php
Labels: bug

#49 Updates to previous PR
  administrator/components/com_j2store/controllers/emailtemplates.php
  administrator/components/com_j2store/helpers/j2html.php
  administrator/components/com_j2store/layouts/edit/email_tab.php
Labels: bug, tidy up

#52 Fix spaces
  administrator/components/com_j2store/controllers/emailtemplates.php
Labels: tidy up

#53 Fix spaces
  administrator/components/com_j2store/helpers/j2html.php
Labels: tidy up

#57 Update shippingmethods.php
  plugins/j2store/shipping_standard/shipping_standard/models/shippingmethods.php
Labels: bug

#55 Products, Orders, Order tmpl - small enhancements
  administrator/components/com_j2store/views/order/tmpl/form.php
  administrator/components/com_j2store/views/order/tmpl/form_general.php
  administrator/components/com_j2store/views/orders/tmpl/default_items.php
  administrator/components/com_j2store/views/products/tmpl/default.php
  administrator/components/com_j2store/views/products/tmpl/default_items.php
Labels: refactoring
