Repository j2commerce/j2cart, pull requests merged in 2024-11, with the labels that each got.

#61 Admin Dashboard UX Improvements
  administrator/components/com_j2store/controllers/productbase.php
  language/backend/en-GB/en-GB.com_j2store.ini
  media/j2store/css/J4/j2store_admin.css
  modules/admin/j2store_chart/tmpl/default.php
  modules/admin/j2store_menu/mod_j2store_menu.xml
  modules/admin/j2store_orders/tmpl/default.php
  modules/admin/j2store_stats/tmpl/default.php
Labels: tidy up, refactoring

#66 UX Improvements to Admin Apps Page
  administrator/components/com_j2store/views/apps/tmpl/default.php
  language/backend/en-GB/en-GB.com_j2store.ini
  media/j2store/css/J4/j2store_admin.css
  modules/admin/j2store_chart/tmpl/default.php
  modules/admin/j2store_orders/tmpl/default.php
  modules/admin/j2store_stats/tmpl/default.php
Labels: refactoring

#81 Removed code preventing error messages to be seen if password issues during registration
  components/com_j2store/views/checkout/tmpl/default.php
Labels: bug

#83 Small update to getDbo to getContainer
  administrator/components/com_j2store/controllers/productbase.php
Labels: refactoring

#82 Admin Catalog Menu and Sub Menu UI Cleanup
  administrator/components/com_j2store/controllers/manufacturers.php
  administrator/components/com_j2store/controllers/vendors.php
  administrator/components/com_j2store/helpers/j2html.php
  administrator/components/com_j2store/helpers/select.php
  administrator/components/com_j2store/layouts/edit/form.php
  administrator/components/com_j2store/layouts/list/default.php
  administrator/components/com_j2store/layouts/list/default_filters.php
  administrator/components/com_j2store/layouts/list/default_items.php
  administrator/components/com_j2store/views/apps/tmpl/default.php
  administrator/components/com_j2store/views/filtergroup/tmpl/form.php
  administrator/components/com_j2store/views/inventories/tmpl/default.php
  administrator/components/com_j2store/views/inventories/tmpl/default_items.php
  administrator/components/com_j2store/views/option/tmpl/form.php
  administrator/components/com_j2store/views/postconfig/tmpl/default.php
  administrator/components/com_j2store/views/postconfig/tmpl/default_advanced.php
  administrator/components/com_j2store/views/postconfig/tmpl/default_basic.php
  administrator/components/com_j2store/views/postconfig/tmpl/default_integrity.php
  administrator/components/com_j2store/views/postconfig/tmpl/default_terms.php
  administrator/components/com_j2store/views/products/tmpl/default.php
  administrator/components/com_j2store/views/products/tmpl/default_advancedfilters.php
  administrator/components/com_j2store/views/products/tmpl/default_filters.php
  administrator/components/com_j2store/views/products/tmpl/default_items.php
  administrator/components/com_j2store/views/shippings/tmpl/shipping_info.php
  administrator/components/com_j2store/views/shippingtroubles/tmpl/default.php
  administrator/components/com_j2store/views/shippingtroubles/tmpl/default_shipping.php
  administrator/components/com_j2store/views/shippingtroubles/tmpl/default_shipping_product.php
  administrator/components/com_j2store/views/shippingtroubles/tmpl/default_steps.php
  language/backend/en-GB/en-GB.com_j2store.ini
  media/j2store/css/J4/j2store_admin.css
Labels: tidy up, refactoring

#85 Added code to remove the old update server site.
  script.j2store.php
Labels: enhancement, tidy up

#86 Removed index.html
  modules/admin/j2store_chart/mod_j2store_chart.xml
  modules/admin/j2store_menu/mod_j2store_menu.xml
  modules/admin/j2store_orders/mod_j2store_orders.xml
  modules/admin/j2store_stats/mod_j2store_stats.xml
  modules/admin/j2store_stats_mini/mod_j2store_stats_mini.xml
  modules/site/mod_j2store_cart/mod_j2store_cart.xml
  modules/site/mod_j2store_currency/mod_j2store_currency.xml
  plugins/content/j2store/j2store.xml
  plugins/finder/j2store/j2store.xml
  plugins/j2store/app_bootstrap3/app_bootstrap3.xml
  plugins/j2store/app_bootstrap4/app_bootstrap4.xml
  plugins/j2store/app_bootstrap5/app_bootstrap5.xml
  plugins/j2store/app_currencyupdater/app_currencyupdater.xml
  plugins/j2store/app_diagnostics/app_diagnostics.xml
  plugins/j2store/app_flexivariable/app_flexivariable.xml
  plugins/j2store/app_localization_data/app_localization_data.xml
  plugins/j2store/app_schemaproducts/app_schemaproducts.xml
  plugins/j2store/payment_banktransfer/payment_banktransfer.xml
  plugins/j2store/payment_cash/payment_cash.xml
  plugins/j2store/payment_moneyorder/payment_moneyorder.xml
  plugins/j2store/payment_paypal/payment_paypal.xml
  plugins/j2store/payment_sagepayform/payment_sagepayform.xml
  plugins/j2store/report_itemised/report_itemised.xml
  plugins/j2store/report_products/report_products.xml
  plugins/j2store/shipping_free/shipping_free.xml
  plugins/j2store/shipping_standard/shipping_standard.xml
  plugins/search/j2store/j2store.xml
  plugins/system/j2pagecache/j2pagecache.xml
  plugins/system/j2store/j2store.xml
  plugins/user/j2userregister/j2userregister.xml
Labels: tidy up

#88 Removed chosen
  administrator/components/com_j2store/controllers/configurations.php
  administrator/components/com_j2store/controllers/coupons.php
  administrator/components/com_j2store/helpers/j2html.php
  administrator/components/com_j2store/layouts/edit/coupon_tab.php
  administrator/components/com_j2store/views/apps/tmpl/default.php
  administrator/components/com_j2store/views/appstores/tmpl/default_item.php
  administrator/components/com_j2store/views/coupon/tmpl/history.php
  administrator/components/com_j2store/views/cpanel/tmpl/default.php
  administrator/components/com_j2store/views/eupdates/tmpl/default.php
  administrator/components/com_j2store/views/order/tmpl/order_items.php
  administrator/components/com_j2store/views/voucher/tmpl/history.php
  fof/render/strapper.php
  plugins/j2store/app_currencyupdater/app_currencyupdater/tmpl/default.php
  plugins/j2store/app_flexivariable/app_flexivariable/tmpl/default.php
  plugins/j2store/report_products/report_products/tmpl/default.php
Labels: tidy up

#87 CSS fixes
  administrator/components/com_j2store/layouts/list/default_filters.php
  administrator/components/com_j2store/views/cpanel/tmpl/default.php
  administrator/components/com_j2store/views/postconfig/tmpl/default.php
  administrator/components/com_j2store/views/products/tmpl/default.php
  language/backend/en-GB/en-GB.com_j2store.ini
  media/j2store/css/backend/editview.css
Labels: bug, tidy up

#92 Miscellaneous fixes from changes made in 4.0.8
  administrator/components/com_j2store/helpers/help.php
  media/j2store/css/J4/j2store_admin.css
  modules/admin/j2store_stats/tmpl/default.php
Labels: tidy up

#94 Orders Category Page Updates
  administrator/components/com_j2store/views/orders/tmpl/default.php
  administrator/components/com_j2store/views/orders/tmpl/default_advancedfilters.php
  administrator/components/com_j2store/views/orders/tmpl/default_filters.php
  administrator/components/com_j2store/views/orders/tmpl/default_items.php
  administrator/components/com_j2store/views/orders/tmpl/print.php
  administrator/components/com_j2store/views/orders/view.csv.php
  administrator/components/com_j2store/views/orders/view.html.php
  language/backend/en-GB/en-GB.com_j2store.ini
  plugins/j2store/report_products/languages/en-GB.plg_j2store_report_products.ini
  plugins/j2store/report_products/report_products/tmpl/default.php
Labels: tidy up, refactoring

#95 Update Admin Orders Module Header button size
  modules/admin/j2store_orders/tmpl/default.php
Labels: enhancement

#96 In custom fields views, allow actions on core custom fields
  administrator/components/com_j2store/controllers/customfields.php
  administrator/components/com_j2store/layouts/list/default_items.php
  language/backend/en-GB/en-GB.com_j2store.ini
Labels: enhancement

#97 Backwards compatibility added to Factory::getContainer()->get('DatabaseDriver') for J3 to migrate
  administrator/components/com_j2store/controllers/productbase.php
  administrator/components/com_j2store/helpers/j2html.php
  administrator/components/com_j2store/helpers/select.php
  administrator/components/com_j2store/layouts/joomla/sidebars/submenu.php
  administrator/components/com_j2store/models/fields/tagtemplatelist.php
  administrator/components/com_j2store/models/fields/templatelist.php
Labels: refactoring

#98 Cannot use DatabaseDriver in Joomla 3
  script.j2store.php
Labels: bug

#99 Revert reintroducing of xhtml
  administrator/components/com_j2store/views/shippingtroubles/tmpl/default_shipping_product.php
Labels: refactoring

#102 Revert function typos fixes to avoid b/c breaks in overrides
  administrator/components/com_j2store/helpers/j2html.php
  administrator/components/com_j2store/models/variants.php
Labels: bug

#114 Support Atum Admin Styles
  media/j2store/css/J4/j2store_admin.css
Labels: bug

#118 Text language string for description
  administrator/components/com_j2store/views/apps/tmpl/default.php
Labels: bug

#119 Revert function name change
  administrator/components/com_j2store/helpers/currency.php
Labels: bug
