Repository j2commerce/j2cart, pull requests merged in 2025-04, with the labels that each got.

#181 Wrong default param values
  script.j2store.php
Labels: bug

#177 Bug Fix - Shopping Cart Hidden Qty
  administrator/components/com_j2store/helpers/product.php
Labels: bug

#182 Admin products id sort
  administrator/components/com_j2store/views/products/tmpl/default_items.php
Labels: bug

#185 Fixes
  administrator/components/com_j2store/controllers/configurations.php
  administrator/components/com_j2store/helpers/product.php
  administrator/components/com_j2store/models/products.php
  administrator/components/com_j2store/version.php
  administrator/components/com_j2store/views/products/tmpl/default_items.php
  j2store.xml
  language/backend/en-GB/en-GB.com_j2store.ini
  language/frontend/en-GB/en-GB.com_j2store.ini
Labels: bug

#184 Change Copyright to LLC
  administrator/components/com_j2store/models/configurations.php
  administrator/components/com_j2store/models/variants.php
  administrator/components/com_j2store/models/vendors.php
  administrator/components/com_j2store/models/vouchers.php
  administrator/components/com_j2store/version.php
  administrator/components/com_j2store/views/apps/tmpl/default.php
  administrator/components/com_j2store/views/filtergroup/tmpl/form.php
  administrator/components/com_j2store/views/option/tmpl/form.php
  administrator/components/com_j2store/views/orders/tmpl/default_advancedfilters.php
  administrator/components/com_j2store/views/orders/tmpl/default_filters.php
  administrator/components/com_j2store/views/orders/tmpl/default_items.php
  administrator/components/com_j2store/views/orders/tmpl/print.php
  administrator/components/com_j2store/views/orders/view.csv.php
  administrator/components/com_j2store/views/orders/view.html.php
  administrator/components/com_j2store/views/postconfig/tmpl/default.php
  administrator/components/com_j2store/views/postconfig/tmpl/default_advanced.php
  administrator/components/com_j2store/views/postconfig/tmpl/default_basic.php
  administrator/components/com_j2store/views/postconfig/tmpl/default_integrity.php
  administrator/components/com_j2store/views/postconfig/tmpl/default_terms.php
  administrator/components/com_j2store/views/product/tmpl/form_confirm_change.php
  administrator/components/com_j2store/views/products/tmpl/default_advancedfilters.php
  administrator/components/com_j2store/views/products/tmpl/default_filters.php
  administrator/components/com_j2store/views/products/tmpl/default_items.php
  administrator/components/com_j2store/views/shippingtroubles/tmpl/default_steps.php
  j2store.xml
  language/frontend/en-GB/en-GB.com_j2store.ini
  modules/admin/j2store_chart/tmpl/default.php
  modules/admin/j2store_menu/mod_j2store_menu.php
  modules/admin/j2store_menu/mod_j2store_menu.xml
  modules/admin/j2store_orders/tmpl/default.php
  modules/admin/j2store_stats/tmpl/default.php
  modules/admin/mod_j2commerce_chart/mod_j2commerce_chart.xml
  plugins/j2store/shipping_standard/shipping_standard/models/shippingmethods.php
  plugins/system/j2store/j2store.php
  script.j2store.php
Labels: tidy up

#186 Duplicate conditions
  administrator/components/com_j2store/helpers/product.php
Labels: bug

#187 Escape error messages to prevent failure of the script push function
  administrator/components/com_j2store/layouts/edit/email_tab.php
  administrator/components/com_j2store/layouts/edit/form.php
  administrator/components/com_j2store/layouts/edit/tab.php
  administrator/components/com_j2store/views/filtergroup/tmpl/form.php
  administrator/components/com_j2store/views/option/tmpl/form.php
  administrator/components/com_j2store/views/product/tmpl/form.php
Labels: bug

#189 Missing fas prevents icons to show properly in Joomla 4
  administrator/components/com_j2store/views/products/tmpl/default_items.php
Labels: bug

#188 'echo include_once' is unnecessary since include_once returns its content without needed echo
  administrator/components/com_j2store/layouts/edit/email_tab.php
Labels: bug

#191 v4.0.14 Additions and fixes
  administrator/components/com_j2store/controllers/configurations.php
  administrator/components/com_j2store/layouts/edit/email_tab.php
  administrator/components/com_j2store/version.php
  administrator/components/com_j2store/views/products/tmpl/default_items.php
  j2store.xml
  language/backend/en-GB/en-GB.com_j2store.ini
  plugins/installer/j2store/j2store.php
  script.j2store.php
Labels: bug

#190 Added script that removes the column campaign_variant_id from the variants table
  script.j2store.php
Labels: bug

#196 Strapper 4 11 25
  administrator/components/com_j2store/helpers/strapper.php
  language/backend/en-GB/en-GB.com_j2store.ini
Labels: bug, tidy up, refactoring

#197 4.0.14fix2
  administrator/components/com_j2store/helpers/strapper.php
  language/backend/en-GB/en-GB.com_j2store.ini
Labels: bug, tidy up, refactoring

#198 [4.0.14] Fixed loading of j2store.css
  administrator/components/com_j2store/helpers/strapper.php
Labels: bug

#199 Fix loading of j2store.css
  administrator/components/com_j2store/helpers/strapper.php
Labels: bug

#200 [4.0.15] Removed row property that may interfere with layouts
  administrator/components/com_j2store/version.php
  j2store.xml
  media/j2store/css/j2store.css
Labels: bug

#202 Typo in 4.1.0-2025-03-02.sql
  administrator/components/com_j2store/sql/updates/mysql/4.1.0-2025-03-02.sql
Labels: bug
