Repository j2commerce/j2cart, pull requests merged in 2025-02, with the labels that each got.

#123 j2html / css tweaks
  administrator/components/com_j2store/helpers/j2html.php
  media/j2store/css/J4/j2store_admin.css
  media/j2store/css/backend/editview.css
Labels: refactoring

#116 Flexi Variant Product Page UI Improvements
  administrator/components/com_j2store/views/product/tmpl/form.php
  administrator/components/com_j2store/views/product/tmpl/form_ajax_avfilter.php
  administrator/components/com_j2store/views/product/tmpl/form_ajax_flexivariableoptions.php
  administrator/components/com_j2store/views/product/tmpl/form_confirm_change.php
  administrator/components/com_j2store/views/product/tmpl/form_filters.php
  administrator/components/com_j2store/views/product/tmpl/form_flexivariable.php
  administrator/components/com_j2store/views/product/tmpl/form_flexivariable_general.php
  administrator/components/com_j2store/views/product/tmpl/form_flexivariable_options.php
  administrator/components/com_j2store/views/product/tmpl/form_flexivariablevariants.php
  administrator/components/com_j2store/views/product/tmpl/form_relations.php
Labels: refactoring

#101 Configuration page updates
  administrator/components/com_j2store/controllers/configurations.php
  administrator/components/com_j2store/controllers/traits/list_view.php
  administrator/components/com_j2store/helpers/currency.php
  administrator/components/com_j2store/layouts/edit/tab.php
  administrator/components/com_j2store/library/popup.php
  administrator/components/com_j2store/library/selectable/base.php
  administrator/components/com_j2store/library/selectable/fields.php
  administrator/components/com_j2store/models/configurations.php
  media/j2store/css/J4/j2store_admin.css
Labels: refactoring

#117 Downloadable Product UI Updates
  administrator/components/com_j2store/views/product/tmpl/form_files.php
  administrator/components/com_j2store/views/product/tmpl/form_general.php
  administrator/components/com_j2store/views/product/tmpl/form_inventory.php
  administrator/components/com_j2store/views/product/tmpl/form_pricing.php
Labels: refactoring

#125 Add form-select to product helper item
  administrator/components/com_j2store/controllers/configurations.php
  administrator/components/com_j2store/helpers/product.php
Labels: refactoring

#147 Translations fixes
  language/backend/en-GB/en-GB.com_j2store.ini
  language/backend/en-GB/en-GB.com_j2store.sys.ini
  language/frontend/en-GB/en-GB.com_j2store.ini
  plugins/j2store/payment_cash/payment_cash.xml
Labels: tidy up

#122 Decimal format is too restrictive for some currencies
  administrator/components/com_j2store/sql/install/mysql/install.j2store.sql
  administrator/components/com_j2store/sql/updates/mysql/4.1.0-2025-02-07.sql
  administrator/components/com_j2store/sql/xml/mysql.xml
  administrator/components/com_j2store/sql/xml/mysqli.xml
Labels: bug

#149 New content tab label
  language/backend/en-GB/en-GB.com_j2store.ini
  plugins/content/j2store/forms/j2store.xml
Labels: refactoring

#153 Added downloadid functionality
  administrator/components/com_j2store/controllers/configurations.php
  language/backend/en-GB/en-GB.com_j2store.ini
  plugins/installer/j2store/j2store.php
Labels: enhancement

#151 Fix deprecated notice when the menu for "Products List View" view doesn't have a Meta Description. #60
  components/com_j2store/controllers/products.php
Labels: tidy up

#152 Refactoring JFactory() in frontend
  components/com_j2store/controllers/callback.php
  components/com_j2store/controllers/carts.php
  components/com_j2store/controllers/checkouts.php
  components/com_j2store/controllers/myprofile.php
  components/com_j2store/controllers/products.php
  components/com_j2store/controllers/producttags.php
  components/com_j2store/models/callback.php
  components/com_j2store/models/vendors.php
  components/com_j2store/router.php
  components/com_j2store/views/carts/tmpl/default.php
  components/com_j2store/views/checkout/tmpl/default.php
  components/com_j2store/views/checkout/tmpl/default_billing.php
  components/com_j2store/views/checkout/tmpl/postpayment.php
  components/com_j2store/views/checkout/view.html.php
  components/com_j2store/views/myprofile/tmpl/address.php
  components/com_j2store/views/myprofile/tmpl/default.php
  components/com_j2store/views/myprofile/tmpl/default_login.php
  components/com_j2store/views/myprofile/tmpl/default_orders.php
  components/com_j2store/views/myprofile/tmpl/orderitems.php
  components/com_j2store/views/myprofile/tmpl/view.php
  components/com_j2store/views/product/tmpl/adminitem_cart.php
  components/com_j2store/views/product/tmpl/item_cart.php
  components/com_j2store/views/product/view.html.php
  components/com_j2store/views/products/view.feed.php
  components/com_j2store/views/products/view.html.php
  components/com_j2store/views/producttags/view.feed.php
  components/com_j2store/views/producttags/view.html.php
  components/com_j2store/views/vendor/view.html.php
Labels: tidy up

#161 Improved menus to allow plugins to add menu items or submenu items in any menu item
  administrator/components/com_j2store/layouts/joomla/sidebars/submenu.php
  modules/admin/j2store_menu/css/j2store_module_menu.css
  modules/admin/j2store_menu/tmpl/default.php
Labels: bug, enhancement, tidy up

#163 Improved messaging and missing elements
  administrator/components/com_j2store/helpers/help.php
Labels: tidy up
