Repository j2commerce/j2cart, pull requests merged in 2025-07, with the labels that each got.

#229 Added missing returns if wrong product type.
  administrator/components/com_j2store/models/behavior/configurable.php
  administrator/components/com_j2store/models/behavior/flexivariable.php
  administrator/components/com_j2store/models/behavior/variable.php
Labels: bug

#235 Article Submission Override Fix
  administrator/components/com_j2store/views/product/tmpl/form.php
Labels: bug

#230 Relative Variant Images
  administrator/components/com_j2store/models/behavior/flexivariable.php
  administrator/components/com_j2store/models/behavior/variable.php
Labels: enhancement

#240 Final changes in product views UX
  administrator/components/com_j2store/views/product/tmpl/form_downloadable.php
  administrator/components/com_j2store/views/product/tmpl/form_flexivariable_options.php
  administrator/components/com_j2store/views/product/tmpl/form_flexivariablevariants.php
  administrator/components/com_j2store/views/product/tmpl/form_variable.php
  administrator/components/com_j2store/views/product/tmpl/form_variable_general.php
  administrator/components/com_j2store/views/product/tmpl/form_variable_options.php
  administrator/components/com_j2store/views/product/tmpl/form_variants.php
Labels: bug, enhancement
