Repository j2commerce/j2cart, pull requests merged in 2025-03, with the labels that each got.

#164 Flexvariant Bulk Checkmark
  administrator/components/com_j2store/views/product/tmpl/form_flexivariablevariants.php
Labels: enhancement

#165 Added ISO 3166-1 numeric column to the countries table
  administrator/components/com_j2store/sql/install/mysql/countries.sql
  administrator/components/com_j2store/sql/install/mysql/install.j2store.sql
  administrator/components/com_j2store/sql/updates/mysql/4.1.0-2025-03-02.sql
  administrator/components/com_j2store/views/countries/tmpl/modal_items.php
  language/backend/en-GB/en-GB.com_j2store.ini
Labels: enhancement

#173 Menu fix for introduced issue when creating 4.1
  administrator/components/com_j2store/layouts/joomla/sidebars/submenu.php
  modules/admin/j2store_menu/tmpl/default.php
Labels: bug

#176 Missing refactoring
  administrator/components/com_j2store/models/orders.php
Labels: refactoring

#166 Additional Image Edit Page Fixes
  administrator/components/com_j2store/views/product/tmpl/form_images.php
Labels: bug

#172 Fix locale error for getTimePickerScript: missing {}
  administrator/components/com_j2store/helpers/strapper.php
Labels: bug

#174 Auto-install modules in the dashboard so they are ready on first use.
  script.j2store.php
Labels: enhancement

#160 Added possibility to export order product options as one column per option
  administrator/components/com_j2store/controllers/configurations.php
  administrator/components/com_j2store/models/orders.php
  language/backend/en-GB/en-GB.com_j2store.ini
Labels: enhancement

#170 Removed property .com_j2store .j2store-product-list .row > * which creates grid issues
  media/j2store/css/j2store.css
Labels: bug

#146 You must specify a non-empty path to clean error
  administrator/components/com_j2store/models/products.php
Labels: bug

#162 Fixed forked key translation error
  language/backend/en-GB/en-GB.com_j2store.ini
Labels: bug

#175 Product Cross Sells / Up Sells
  administrator/components/com_j2store/helpers/product.php
Labels: bug
