Repository j2commerce/j2cart, pull requests merged in 2025-06, with the labels that each got.

#213 Order search
  administrator/components/com_j2store/models/orders.php
Labels: enhancement

#216 Inclusion of #213 into 4.0.16
  administrator/components/com_j2store/models/orders.php
Labels: enhancement

#218 Ensure File::getExt can be called properly in Joomla 4 AND over
  administrator/components/com_j2store/helpers/email.php
  administrator/components/com_j2store/helpers/invoice.php
  administrator/components/com_j2store/models/emailtemplates.php
Labels: bug

#217 Fixed fontawesome may not be present in the asset array
  administrator/components/com_j2store/helpers/strapper.php
Labels: bug

#222 Add data-menu-key attribute to menu items for easy targeting in guided tours
  administrator/components/com_j2store/layouts/joomla/sidebars/submenu.php
  modules/admin/j2store_menu/tmpl/default.php
Labels: enhancement

#221 Translate the module title in addModuleToPosition()
  script.j2store.php
Labels: bug

#223 Move Finder to new plugin architecture
  plugins/finder/j2store/elements/j2storemenuitem.php
  plugins/finder/j2store/j2store.php
  plugins/finder/j2store/j2store.xml
  plugins/finder/j2store/services/provider.php
  plugins/finder/j2store/src/Extension/J2store.php
  plugins/finder/j2store/src/Field/J2storemenuitemField.php
Labels: bug, refactoring

#220 Database modifications: decimals (15,5), duplicate queries, ordering and enabled column fixes
  administrator/components/com_j2store/sql/install/mysql/install.j2store.sql
  administrator/components/com_j2store/sql/updates/mysql/4.1.0-2025-02-07.sql
  administrator/components/com_j2store/sql/updates/mysql/4.1.0-2025-06-13.sql
  administrator/components/com_j2store/sql/xml/mysql.xml
  administrator/components/com_j2store/sql/xml/mysqli.xml
Labels: enhancement, refactoring

#224 Product options: add message if no option has been created yet
  administrator/components/com_j2store/views/product/tmpl/form_configoptions.php
  administrator/components/com_j2store/views/product/tmpl/form_flexivariable_options.php
  administrator/components/com_j2store/views/product/tmpl/form_options.php
  administrator/components/com_j2store/views/product/tmpl/form_variable_options.php
  language/backend/en-GB/en-GB.com_j2store.ini
Labels: enhancement

#225 Checklist: Add fallback colors to progress bar to be usable in Joomla 4
  modules/admin/mod_j2commerce_checklist/tmpl/default.php
Labels: bug

#226 Removed the keyword 'COLUMN' to be more universal
  administrator/components/com_j2store/sql/updates/mysql/4.1.0-2025-06-13.sql
Labels: bug

#227 Use 'CHANGE' instead of MODIFY
  administrator/components/com_j2store/sql/updates/mysql/4.1.0-2025-06-13.sql
Labels: bug
